# Generated by Django 6.0.4 on 2026-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name'], name='profiles_name_6d24ba_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_gender_3ecb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id'], name='profiles_country_d0a8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age_group'], name='profiles_age_gro_af31b0_idx'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
